import type { CvRenderData } from "@cv-maker/contracts";

/**
 * A single, richly-filled example CV, used to power the template gallery's
 * thumbnails and preview modal (see TemplateCard.tsx / TemplatePreviewModal.tsx).
 *
 * Deliberately NOT derived from the signed-in user's real CV: whatever stage
 * a visitor's own draft is at (empty, half-filled, or complete), every
 * template should still show up looking like a finished, professional CV.
 * Template *selection* itself still operates on the real CV/render-data —
 * this constant is for preview/thumbnail purposes only.
 *
 * `templateId` / `accentColor` are placeholders here — every call site
 * overrides both per-template/per-color before passing this to <CvDocument>.
 */

const TIMESTAMP = "2026-01-15T09:00:00.000Z";

/** A tasteful, self-contained placeholder avatar (inline SVG data URI, no
 * network request) — neutral navy tones so it reads fine under any
 * template's accent color. */
const AVATAR_SVG = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#25406e"/><stop offset="1" stop-color="#0a1628"/></linearGradient></defs><rect width="200" height="200" fill="url(#g)"/><text x="100" y="126" font-family="Georgia, 'Times New Roman', serif" font-size="78" fill="#f4ede4" text-anchor="middle">MD</text></svg>`;
export const DEMO_PHOTO_URL = `data:image/svg+xml,${encodeURIComponent(AVATAR_SVG)}`;

export const DEMO_CV_RENDER_DATA: CvRenderData = {
  contentLanguage: "en",
  templateId: "helsinki",
  accentColor: "#0A1628",
  watermarked: false,
  personalInfo: {
    firstName: "Mariana",
    lastName: "Duarte",
    email: "mariana.duarte@example.com",
    address: null,
    phone: "+351 912 345 678",
    postalCode: null,
    city: "Lisbon, Portugal",
    dateOfBirth: null,
    placeOfBirth: null,
    drivingLicence: null,
    gender: null,
    genderSelfDescribed: null,
    nationality: "Portuguese",
    maritalStatus: null,
    linkedin: "linkedin.com/in/marianaduarte",
    website: "marianaduarte.design",
    photoUrl: DEMO_PHOTO_URL,
    photoCrop: null,
  },
  sections: [
    {
      id: "b49d6815-ce40-4b02-a002-bd63b2d32cfc",
      cvId: "955350e4-7227-436d-a12c-d21b23aaa8b9",
      type: "profile_summary",
      displayName: null,
      sortOrder: 0,
      hidden: false,
      forcePageBreak: false,
      organizeChronologically: false,
      deletable: false,
      settings: {},
      createdAt: TIMESTAMP,
      updatedAt: TIMESTAMP,
      freeformDescription:
        "<p>Product designer with over eight years shaping digital tools for fast-growing teams. I turn fuzzy problems into clear, usable interfaces and work closely with engineering and research from the first sketch to the shipped release. Most recently led design for a B2B analytics platform used by more than 40,000 monthly active users.</p>",
    },
    {
      id: "761904dc-9f25-4d1e-8e5d-ea7ffbdd8484",
      cvId: "955350e4-7227-436d-a12c-d21b23aaa8b9",
      type: "work_experience",
      displayName: null,
      sortOrder: 1,
      hidden: false,
      forcePageBreak: false,
      organizeChronologically: true,
      deletable: false,
      settings: {},
      createdAt: TIMESTAMP,
      updatedAt: TIMESTAMP,
      workExperienceEntries: [
        {
          id: "ba4c08db-0ea5-4ac1-82ed-8c01e6ae235e",
          sectionId: "761904dc-9f25-4d1e-8e5d-ea7ffbdd8484",
          title: "Senior Product Designer",
          employer: "Northwind Analytics",
          city: "Lisbon",
          dateRange: { start: { granularity: "full", month: 8, year: 2022 }, end: { isPresent: true } },
          description:
            "<p>Leading design for a B2B analytics platform used daily by 40,000+ people. Rebuilt the core reporting flow, cutting average time-to-first-insight by 35%. Introduced a shared design system now used by three product teams.</p><ul><li>Partnered with engineering and data science on a full IA redesign</li><li>Ran monthly usability studies that shaped the roadmap</li><li>Mentored two junior designers</li></ul>",
          sortOrder: 0,
          createdAt: TIMESTAMP,
          updatedAt: TIMESTAMP,
        },
        {
          id: "9c7472e0-1c0f-4cb9-9a9c-edf798d949dc",
          sectionId: "761904dc-9f25-4d1e-8e5d-ea7ffbdd8484",
          title: "Product Designer",
          employer: "Vela Studio",
          city: "Porto",
          dateRange: {
            start: { granularity: "full", month: 1, year: 2019 },
            end: { isPresent: false, granularity: "full", month: 7, year: 2022 },
          },
          description:
            "<p>Designed end-to-end flows for a portfolio of client products, from early discovery through to launch and iteration.</p><ul><li>Owned design for 6 client products across fintech and travel</li><li>Built the studio's first reusable component library</li></ul>",
          sortOrder: 1,
          createdAt: TIMESTAMP,
          updatedAt: TIMESTAMP,
        },
        {
          id: "32006c3f-9664-4fb8-9196-8afd3557ff9a",
          sectionId: "761904dc-9f25-4d1e-8e5d-ea7ffbdd8484",
          title: "UX Designer",
          employer: "Ardent Digital",
          city: "Lisbon",
          dateRange: {
            start: { granularity: "full", month: 3, year: 2016 },
            end: { isPresent: false, granularity: "full", month: 12, year: 2018 },
          },
          description:
            "<p>First design hire at a 20-person agency. Set up research practices and delivered UX work for a dozen client engagements.</p>",
          sortOrder: 2,
          createdAt: TIMESTAMP,
          updatedAt: TIMESTAMP,
        },
      ],
    },
    {
      id: "7b457ade-073e-42fe-9b9a-7de6c09b7751",
      cvId: "955350e4-7227-436d-a12c-d21b23aaa8b9",
      type: "education",
      displayName: null,
      sortOrder: 2,
      hidden: false,
      forcePageBreak: false,
      organizeChronologically: true,
      deletable: false,
      settings: {},
      createdAt: TIMESTAMP,
      updatedAt: TIMESTAMP,
      educationEntries: [
        {
          id: "ee594cc6-00d5-4f9b-8c27-71b3522721b1",
          sectionId: "7b457ade-073e-42fe-9b9a-7de6c09b7751",
          degree: "MSc in Interaction Design",
          school: "Universidade do Porto",
          city: "Porto",
          dateRange: {
            start: { granularity: "full", month: 9, year: 2014 },
            end: { isPresent: false, granularity: "full", month: 6, year: 2016 },
          },
          description: "<p>Thesis on adaptive interfaces for low-connectivity environments.</p>",
          sortOrder: 0,
          createdAt: TIMESTAMP,
          updatedAt: TIMESTAMP,
        },
        {
          id: "0d131751-d1c7-449b-aa8c-c83e28fe9594",
          sectionId: "7b457ade-073e-42fe-9b9a-7de6c09b7751",
          degree: "BA in Communication Design",
          school: "Instituto Politécnico de Lisboa",
          city: "Lisbon",
          dateRange: {
            start: { granularity: "full", month: 9, year: 2010 },
            end: { isPresent: false, granularity: "full", month: 6, year: 2014 },
          },
          description: null,
          sortOrder: 1,
          createdAt: TIMESTAMP,
          updatedAt: TIMESTAMP,
        },
      ],
    },
    {
      id: "9b63403c-47a0-480a-84e3-e1a92b99e20e",
      cvId: "955350e4-7227-436d-a12c-d21b23aaa8b9",
      type: "skills",
      displayName: null,
      sortOrder: 3,
      hidden: false,
      forcePageBreak: false,
      organizeChronologically: false,
      deletable: false,
      settings: {},
      createdAt: TIMESTAMP,
      updatedAt: TIMESTAMP,
      skillEntries: [
        {
          id: "b38e1a38-dd57-4ea7-bcbf-044742b9ebc3",
          sectionId: "9b63403c-47a0-480a-84e3-e1a92b99e20e",
          name: "User Research",
          level: 5,
          sortOrder: 0,
          createdAt: TIMESTAMP,
          updatedAt: TIMESTAMP,
        },
        {
          id: "33c40e48-5900-4704-aad1-09a8f7de9c12",
          sectionId: "9b63403c-47a0-480a-84e3-e1a92b99e20e",
          name: "Design Systems",
          level: 5,
          sortOrder: 1,
          createdAt: TIMESTAMP,
          updatedAt: TIMESTAMP,
        },
        {
          id: "fb51aba1-bd88-4f13-a827-5ea94d8a4d36",
          sectionId: "9b63403c-47a0-480a-84e3-e1a92b99e20e",
          name: "Figma",
          level: 5,
          sortOrder: 2,
          createdAt: TIMESTAMP,
          updatedAt: TIMESTAMP,
        },
        {
          id: "98646114-cfe4-430a-9631-e1a0167c2a83",
          sectionId: "9b63403c-47a0-480a-84e3-e1a92b99e20e",
          name: "Prototyping",
          level: 4,
          sortOrder: 3,
          createdAt: TIMESTAMP,
          updatedAt: TIMESTAMP,
        },
        {
          id: "83e3cf20-c5f9-425e-b8cf-0550c8f30016",
          sectionId: "9b63403c-47a0-480a-84e3-e1a92b99e20e",
          name: "Data Visualization",
          level: 4,
          sortOrder: 4,
          createdAt: TIMESTAMP,
          updatedAt: TIMESTAMP,
        },
        {
          id: "141aa028-3413-4857-b7ea-e2ad9b7157b0",
          sectionId: "9b63403c-47a0-480a-84e3-e1a92b99e20e",
          name: "Front-end (HTML/CSS)",
          level: 3,
          sortOrder: 5,
          createdAt: TIMESTAMP,
          updatedAt: TIMESTAMP,
        },
      ],
    },
    {
      id: "178e9cc4-0fae-435e-8927-67bfeea13e58",
      cvId: "955350e4-7227-436d-a12c-d21b23aaa8b9",
      type: "languages",
      displayName: null,
      sortOrder: 4,
      hidden: false,
      forcePageBreak: false,
      organizeChronologically: false,
      deletable: true,
      settings: {},
      createdAt: TIMESTAMP,
      updatedAt: TIMESTAMP,
      languageEntries: [
        {
          id: "19defcac-834f-40da-a6d2-cf98af07809f",
          sectionId: "178e9cc4-0fae-435e-8927-67bfeea13e58",
          languageName: "Portuguese",
          proficiency: { scale: "descriptive", level: "native" },
          sortOrder: 0,
          createdAt: TIMESTAMP,
          updatedAt: TIMESTAMP,
        },
        {
          id: "9ce3c56d-4e28-422d-973b-1901ae377a53",
          sectionId: "178e9cc4-0fae-435e-8927-67bfeea13e58",
          languageName: "English",
          proficiency: { scale: "cefr", level: "C1" },
          sortOrder: 1,
          createdAt: TIMESTAMP,
          updatedAt: TIMESTAMP,
        },
        {
          id: "e7065363-d61d-4726-bdf4-8a0eb61129a9",
          sectionId: "178e9cc4-0fae-435e-8927-67bfeea13e58",
          languageName: "Spanish",
          proficiency: { scale: "cefr", level: "B2" },
          sortOrder: 2,
          createdAt: TIMESTAMP,
          updatedAt: TIMESTAMP,
        },
      ],
    },
    {
      id: "215643c1-697a-4589-82e3-16bb0f685149",
      cvId: "955350e4-7227-436d-a12c-d21b23aaa8b9",
      type: "hobbies",
      displayName: null,
      sortOrder: 5,
      hidden: false,
      forcePageBreak: false,
      organizeChronologically: false,
      deletable: false,
      settings: {},
      createdAt: TIMESTAMP,
      updatedAt: TIMESTAMP,
      hobbyEntries: [
        {
          id: "23c869dc-b7e6-46c8-8c0f-06b5caa66c31",
          sectionId: "215643c1-697a-4589-82e3-16bb0f685149",
          name: "Trail running",
          sortOrder: 0,
          createdAt: TIMESTAMP,
          updatedAt: TIMESTAMP,
        },
        {
          id: "60ae5de4-d906-4c2c-b0f2-7d93778e4460",
          sectionId: "215643c1-697a-4589-82e3-16bb0f685149",
          name: "Analog photography",
          sortOrder: 1,
          createdAt: TIMESTAMP,
          updatedAt: TIMESTAMP,
        },
      ],
    },
    {
      id: "5db72771-055e-4433-b5c9-24f8b48c2f35",
      cvId: "955350e4-7227-436d-a12c-d21b23aaa8b9",
      type: "references",
      displayName: null,
      sortOrder: 6,
      hidden: false,
      forcePageBreak: false,
      organizeChronologically: false,
      deletable: false,
      settings: { showAvailableUponRequest: true },
      createdAt: TIMESTAMP,
      updatedAt: TIMESTAMP,
      referenceEntries: [],
    },
  ],
};
